FROM rust:latest AS builder

WORKDIR /app
COPY .cargo .cargo
COPY ./server ./server
COPY ./crate ./crate
COPY Cargo.toml . 
COPY Cargo.lock .

RUN cargo build --bin server -F instrumentation

# RUNNER
FROM rust:latest

WORKDIR /app

COPY --from=builder /app/target/debug/server ./

EXPOSE 9003

CMD ["./server"]


